### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by Sabre142** [nullfoxh/NWTooltipFix#1]
[Deleted]

**Comment by nullfoxh** [comment]
![image](https://user-images.githubusercontent.com/12772977/50651189-4ab8b300-0f8b-11e9-905b-97d9a5ad4b7c.png)
Seems to be working for me..
Are you using the latest version?

**Comment by Sabre142** [comment]
That's weird

I'm using the 2.0.3 version of AtlasLoot uploaded on NW forums.

**Comment by nullfoxh** [comment]
Oh I meant latest version of NWTooltipFix. 
Latest is v1.1.

**Comment by Sabre142** [comment]
using 1.1

strange it doesn't work for me

**Comment by nullfoxh** [comment]
Is it working on items outside of Atlasloot though?

**Comment by Sabre142** [comment]
Yes.

**Comment by nullfoxh** [comment]
Could you please try this version and see if it works for you? I changed the way it's loading the Atlasloot hook. Remove the old folder, since this one is named !NWTooltipFix.
[!NWTooltipFix.zip](https://github.com/nullfoxh/NWTooltipFix/files/2727354/NWTooltipFix.zip)

**Comment by Sabre142** [comment]
I'm afraid it didn't work.

**Comment by nullfoxh** [comment]
hmm. Any chance you could upload the version of atlasloot you're using and I'll try with it. I should be using the same version but who knows. Could be some other addon conflicting too.

**Comment by Sabre142** [comment]
https://drive.google.com/file/d/0B6YakV44QAkNeUV1X2dENkZrcUE/view

**Comment by nullfoxh** [comment]
Thank you so much for the report.
I believe this will fix the issue. 
If you could confirm I could make an update to the addon for all to use.
[!NWTooltipFix.zip](https://github.com/nullfoxh/NWTooltipFix/files/2727735/NWTooltipFix.zip)

**Comment by Sabre142** [comment]
It worked, thanks.

**Comment by nullfoxh** [comment]
Should be fixed in v1.2.
