### ISSUE TITLE
Doesn't work for enchants, gems and socket bonuses

### ISSUE THREAD

**Issue by t-schroeder** [nullfoxh/NWTooltipFix#2]
I don't know if this is still in the scope of this addon but i guess these other things should also give only +heal and no +dmg.
![image](https://user-images.githubusercontent.com/24255259/59305334-59be3280-8c9a-11e9-9080-5bafa9070560.png)
![image](https://user-images.githubusercontent.com/24255259/59305521-b15c9e00-8c9a-11e9-867b-031cd847fa4f.png)
![image](https://user-images.githubusercontent.com/24255259/59305675-039dbf00-8c9b-11e9-924d-477f9846efce.png)

**Comment by nullfoxh** [comment]
Yeah those are not reverted to their 2.1 states serverside last I asked so working as intended.
